#!/usr/bin/perl -w

use strict;
use diagnostics;

my @args=@ARGV;
my $numargs=$#ARGV;
my $curarg=0;
my $filename;
my $newname;
my $newend=".sxw";

print "Converting...\n";

while ($curarg <= $numargs){
    $filename=$args[$curarg];
    $newname=$filename;
    if (!($newname=~ s/(\.\w*)$/$newend/)){
	$newname=$newname.$newend;
    }
    print "$filename => $newname\n";
    system "wpd2sxw $filename $newname";
    ++$curarg;
}












